from enum import Enum, auto


class CoordinateSystem(Enum):
    """
    Defines the geometric coordinate space in which an Ops object was
    generated.
    """

    PIXEL_SPACE = auto()
    """
    An intermediate coordinate system for raster-based operations.

    - **Unit**: Pixels.
    - **Origin (0,0)**: Top-left corner of the source bitmap surface.
    - **Use**: Used by producers that trace raster images. The
      `source_dimensions` will be the width and height of the bitmap
      in pixels.
    """

    MILLIMETER_SPACE = auto()
    """
    The canonical coordinate system for all local vector geometry.

    This is the standard space for `workpiece.boundaries` and any scalable ops
    generated by a producer.

    - **Unit**: Millimeters (mm).
    - **Origin (0,0)**: The bottom-left corner anchor of the workpiece.
    - **Orientation**: Y-axis pointing upwards (a standard Cartesian system).
    - **Use**: This is the contract for importers and for producers that
      output scalable vector geometry (`is_scalable=True`). The
      `source_dimensions` will be the width and height of the workpiece's
      "canvas" in millimeters.
    """
