version: 2
updates:
  - directory: /website
    package-ecosystem: "npm"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"

  - directory: /
    package-ecosystem: "pip"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      python-dependencies:
        patterns:
          - "*"
