from typing import List, Tuple, Optional, Union

Point = Tuple[int, int]
Path = List[Point]
Paths = List[Path]

PFT_EVENODD: int
PFT_NONZERO: int
PFT_POSITIVE: int
PFT_NEGATIVE: int

CT_INTERSECTION: int
CT_UNION: int
CT_DIFFERENCE: int
CT_XOR: int

JT_SQUARE: int
JT_ROUND: int
JT_MITER: int

ET_CLOSEDPOLYGON: int
ET_OPENBUTT: int
ET_OPENSQUARE: int
ET_OPENROUND: int

PT_SUBJECT: int
PT_CLIP: int

PYCLIPPER_ADD_PATH_CLIP_TYPE_SUBJECT: int
PYCLIPPER_ADD_PATH_CLIP_TYPE_CLIP: int

def Orientation(path: Path) -> bool: ...
def Area(path: Path) -> float: ...
def PointInPolygon(point: Point, polygon: Path) -> int: ...
def SimplifyPolygon(path: Path, fillType: int = ...) -> Paths: ...
def SimplifyPolygons(paths: Paths, fillType: int = ...) -> Paths: ...
def CleanPolygon(path: Path, distance: float = ...) -> Path: ...
def CleanPolygons(paths: Paths, distance: float = ...) -> Paths: ...
def ReversePath(path: Path) -> Path: ...
def ReversePaths(paths: Paths) -> Paths: ...

class Pyclipper:
    def __init__(self) -> None: ...
    def AddPath(self, path: Path, polyType: int, closed: bool) -> None: ...
    def AddPaths(self, paths: Paths, polyType: int, closed: bool) -> None: ...
    def GetBounds(self) -> "IntRect": ...
    def Execute(
        self, clipType: int, subjFillType: int = ..., clipFillType: int = ...
    ) -> Paths: ...
    def Clear(self) -> None: ...

class PyclipperOffset:
    def __init__(
        self, miterLimit: float = ..., arcTolerance: float = ...
    ) -> None: ...
    def AddPath(self, path: Path, joinType: int, endType: int) -> None: ...
    def AddPaths(self, paths: Paths, joinType: int, endType: int) -> None: ...
    def Execute(self, delta: float) -> Paths: ...
    def Clear(self) -> None: ...

class IntRect:
    left: int
    top: int
    right: int
    bottom: int
    def __init__(self) -> None: ...
