#!/bin/sh
set -e

#DEBHELPER#

if [ "$1" = "configure" ]; then
    update-desktop-database -q || true
    gtk-update-icon-cache -q /usr/share/icons/hicolor || true
    update-mime-database /usr/share/mime || true
fi

exit 0
