from __future__ import annotations
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, Dict, List, Optional


@dataclass
class VectorizationSpec(ABC):
    """Base class for defining how vectors are generated."""

    @abstractmethod
    def to_dict(self) -> Dict[str, Any]:
        """Serializes the specification to a dictionary."""
        raise NotImplementedError

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "VectorizationSpec":
        """Factory to create a VectorizationSpec instance from a dictionary."""
        spec_type = data.get("type")
        if not spec_type:
            raise ValueError("VectorizationSpec dict must have a 'type' key.")

        if spec_type == "TraceSpec":
            return TraceSpec.from_dict(data)
        elif spec_type == "PassthroughSpec":
            return PassthroughSpec.from_dict(data)
        elif spec_type == "ProceduralSpec":
            return ProceduralSpec.from_dict(data)
        else:
            raise ValueError(f"Unknown VectorizationSpec type: {spec_type}")


@dataclass
class TraceSpec(VectorizationSpec):
    """Specifies that vectors should be generated by tracing a bitmap."""

    threshold: float = 0.5
    auto_threshold: bool = True
    invert: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return {
            "type": "TraceSpec",
            "threshold": self.threshold,
            "auto_threshold": self.auto_threshold,
            "invert": self.invert,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "TraceSpec":
        return cls(
            threshold=data.get("threshold", 0.5),
            auto_threshold=data.get("auto_threshold", True),
            invert=data.get("invert", False),
        )


@dataclass
class PassthroughSpec(VectorizationSpec):
    """
    Specifies that vectors should be parsed directly from a vector source.
    """

    active_layer_ids: Optional[List[str]] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "type": "PassthroughSpec",
            "active_layer_ids": self.active_layer_ids,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "PassthroughSpec":
        return cls(active_layer_ids=data.get("active_layer_ids"))


@dataclass
class ProceduralSpec(VectorizationSpec):
    """Specifies that vectors are generated by a procedural function."""

    def to_dict(self) -> Dict[str, Any]:
        return {"type": "ProceduralSpec"}

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ProceduralSpec":
        return cls()
