from __future__ import annotations
from abc import ABC, abstractmethod
from dataclasses import dataclass
from enum import Enum
from typing import Any, Dict, List, Optional


class LayerImportMode(Enum):
    """Determines how imported layers are mapped into the document."""

    MAP_TO_EXISTING = "map_to_existing"
    NEW_LAYERS = "new_layers"
    FLATTEN = "flatten"


@dataclass
class VectorizationSpec(ABC):
    """Base class for defining how vectors are generated."""

    ppi: float = 96.0

    @abstractmethod
    def to_dict(self) -> Dict[str, Any]:
        """Serializes the specification to a dictionary."""
        raise NotImplementedError

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "VectorizationSpec":
        """Factory to create a VectorizationSpec instance from a dictionary."""
        spec_type = data.get("type")
        if not spec_type:
            raise ValueError("VectorizationSpec dict must have a 'type' key.")

        if spec_type == "TraceSpec":
            return TraceSpec.from_dict(data)
        elif spec_type == "PassthroughSpec":
            return PassthroughSpec.from_dict(data)
        elif spec_type == "ProceduralSpec":
            return ProceduralSpec.from_dict(data)
        else:
            raise ValueError(f"Unknown VectorizationSpec type: {spec_type}")


@dataclass
class TraceSpec(VectorizationSpec):
    """Specifies that vectors should be generated by tracing a bitmap."""

    threshold: float = 0.5
    auto_threshold: bool = True
    invert: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return {
            "type": "TraceSpec",
            "threshold": self.threshold,
            "auto_threshold": self.auto_threshold,
            "invert": self.invert,
            "ppi": self.ppi,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "TraceSpec":
        return cls(
            threshold=data.get("threshold", 0.5),
            auto_threshold=data.get("auto_threshold", True),
            invert=data.get("invert", False),
            ppi=data.get("ppi", 96.0),
        )


@dataclass
class PassthroughSpec(VectorizationSpec):
    """
    Specifies that vectors should be parsed directly from a vector source.
    """

    active_layer_ids: Optional[List[str]] = None
    layer_import_mode: LayerImportMode = LayerImportMode.MAP_TO_EXISTING
    trim_padding: float = 0.01

    def to_dict(self) -> Dict[str, Any]:
        return {
            "type": "PassthroughSpec",
            "active_layer_ids": self.active_layer_ids,
            "layer_import_mode": self.layer_import_mode.value,
            "trim_padding": self.trim_padding,
            "ppi": self.ppi,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "PassthroughSpec":
        mode_str = data.get("layer_import_mode")
        if mode_str:
            mode = LayerImportMode(mode_str)
        elif "create_new_layers" in data:
            mode = (
                LayerImportMode.NEW_LAYERS
                if data["create_new_layers"]
                else LayerImportMode.FLATTEN
            )
        else:
            mode = LayerImportMode.MAP_TO_EXISTING
        return cls(
            active_layer_ids=data.get("active_layer_ids"),
            layer_import_mode=mode,
            trim_padding=data.get("trim_padding", 0.01),
            ppi=data.get("ppi", 96.0),
        )


@dataclass
class ProceduralSpec(VectorizationSpec):
    """Specifies that vectors are generated by a procedural function."""

    def to_dict(self) -> Dict[str, Any]:
        return {"type": "ProceduralSpec", "ppi": self.ppi}

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ProceduralSpec":
        return cls(ppi=data.get("ppi", 96.0))
