#!/usr/bin/env python3
"""Generate Blender setup script for video project assembly.

This script creates a Blender Python script that sets up a video editing
project with clips, audio tracks, and text overlays from a CHANGELOG.md.
"""

import argparse
import sys
from pathlib import Path


def parse_changelog(changelog_path):
    """Parse CHANGELOG.md to extract version headers and content.

    Args:
        changelog_path: Path to CHANGELOG.md file.

    Returns:
        List of tuples: (version, content_lines).
    """
    changelog_path = Path(changelog_path)

    if not changelog_path.exists():
        msg = f"Error: CHANGELOG.md not found at '{changelog_path}'"
        print(msg, file=sys.stderr)
        return []

    sections = []
    current_version = None
    current_content = []

    with open(changelog_path, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip()
            if line.startswith("## ["):
                if current_version is not None:
                    sections.append((current_version, current_content))
                current_version = line[4:].split("]")[0]
                current_content = []
            elif current_version is not None:
                current_content.append(line)

    if current_version is not None:
        sections.append((current_version, current_content))

    return sections


def find_media_files(media_dir, extensions=(".mp4", ".mkv", ".mov", ".avi")):
    """Find video files in media directory.

    Args:
        media_dir: Path to media directory.
        extensions: Tuple of video file extensions to include.

    Returns:
        Sorted list of video file paths.
    """
    media_dir = Path(media_dir)

    if not media_dir.exists():
        msg = f"Error: Media directory '{media_dir}' does not exist"
        print(msg, file=sys.stderr)
        return []

    video_files = []
    for ext in extensions:
        video_files.extend(media_dir.glob(f"*{ext}"))

    return sorted(video_files)


def find_previous_blend_file(release_dir):
    """Find the previous release's blend file.

    Args:
        release_dir: Path to current release directory.

    Returns:
        Path to previous blend file or None.
    """
    media_dir = Path(__file__).parent.parent / "media"
    if not media_dir.exists():
        return None

    release_dirs = sorted(
        [d for d in media_dir.iterdir() if d.is_dir()],
        key=lambda x: x.name,
        reverse=True,
    )

    for release in release_dirs:
        if release == release_dir:
            continue
        blend_file = release / "draft_edit.blend"
        if blend_file.exists():
            return blend_file
    return None


def find_thumbnail(release_dir):
    """Find the thumbnail for the current release.

    Args:
        release_dir: Path to current release directory.

    Returns:
        Path to thumbnail file or None.
    """
    release_dir = Path(release_dir)
    drafts_dir = release_dir / "drafts"
    if drafts_dir.exists():
        for i in range(1, 6):
            thumbnail = drafts_dir / f"thumbnail{i}.png"
            if thumbnail.exists():
                return thumbnail
    return None


def generate_blender_script(
    media_dir,
    output_blend,
    changelog_path=None,
    resolution_x=1920,
    resolution_y=1080,
    fps=30,
    template_path=None,
    thumbnail_path=None,
):
    """Generate Blender Python script content.

    Args:
        media_dir: Path to media directory containing video files.
        output_blend: Path for output .blend file.
        changelog_path: Path to CHANGELOG.md for text overlays.
        resolution_x: Video width in pixels.
        resolution_y: Video height in pixels.
        fps: Frames per second.
        template_path: Path to template .blend file.
        thumbnail_path: Path to thumbnail image.

    Returns:
        String containing the Blender Python script.
    """
    media_dir = Path(media_dir).resolve()
    output_blend = Path(output_blend).resolve()
    video_files = find_media_files(media_dir)

    if not video_files:
        msg = f"Warning: No video files found in '{media_dir}'"
        print(msg, file=sys.stderr)

    changelog_sections = []
    if changelog_path:
        changelog_sections = parse_changelog(changelog_path)

    script_lines = [
        '"""Blender setup script generated by generate_blender_setup.py."""',
        "",
        "import bpy",
        "import os",
        "",
        "",
        "def load_template(template_path):",
        '    """Load template blend file."""',
        "    if template_path and os.path.exists(template_path):",
        "        bpy.ops.wm.open_mainfile(filepath=template_path)",
        "        return True",
        "    return False",
        "",
        "",
        "def clear_sequencer():",
        '    """Clear all strips from the video sequencer."""',
        "    if bpy.context.scene.sequence_editor is None:",
        "        bpy.context.scene.sequence_editor_create()",
        "    ",
        "    bpy.ops.sequencer.select_all(action='SELECT')",
        "    bpy.ops.sequencer.delete()",
        "",
        "",
        "def setup_scene_settings(res_x, res_y, fps_val):",
        '    """Configure render settings."""',
        "    bpy.context.scene.render.resolution_x = res_x",
        "    bpy.context.scene.render.resolution_y = res_y",
        "    bpy.context.scene.render.fps = fps_val",
        "    bpy.context.scene.render.image_settings.file_format = 'FFMPEG'",
        "    bpy.context.scene.render.ffmpeg.format = 'MPEG4'",
        "    bpy.context.scene.render.ffmpeg.codec = 'H264'",
        "",
        "",
        "def add_thumbnail(thumbnail_path):",
        '    """Add thumbnail as first frame."""',
        "    if not thumbnail_path or not os.path.exists(thumbnail_path):",
        "        return 1",
        "    ",
        "    bpy.ops.sequencer.image_strip_add(",
        "        filepath=thumbnail_path,",
        "        frame_start=1,",
        "        channel=1,",
        "        frame_end=1,",
        "    )",
        "    return 2",
        "",
        "",
        "def add_video_clips(media_dir, video_files, start_frame):",
        '    """Add video clips to the timeline."""',
        "    current_frame = start_frame",
        "    track_video = 1",
        "    track_audio = 2",
        "    ",
        "    for filepath in video_files:",
        "        filename = os.path.basename(filepath)",
        "        full_path = os.path.join(media_dir, filename)",
        "        ",
        "        # Add movie strip (video + audio)",
        "        bpy.ops.sequencer.movie_strip_add(",
        "            filepath=full_path,",
        "            frame_start=current_frame,",
        "            channel=track_video,",
        "            sound=True,",
        "        )",
        "        ",
        "        # Move audio to separate track",
        "        strip = bpy.context.scene.sequence_editor.active_strip",
        "        if strip.sound:",
        "            audio_strip = strip.sound",
        "            audio_strip.channel = track_audio",
        "        ",
        "        # Update current frame for next clip",
        "        current_frame += strip.frame_final_duration",
        "    ",
        "    return current_frame - 1",
        "",
        "",
        "def add_text_overlays(sections, start_frame, duration=180):",
        '    """Add text strips from changelog sections."""',
        "    if not sections:",
        "        return",
        "    ",
        "    track_text = 3",
        "    current_frame = start_frame",
        "    ",
        "    for version, content in sections:",
        "        # Create title text",
        '        title_text = f"Release {version}"',
        "        ",
        "        bpy.ops.sequencer.text_strip_add(",
        "            frame_start=current_frame,",
        "            channel=track_text,",
        "        )",
        "        ",
        "        strip = bpy.context.scene.sequence_editor.active_strip",
        "        strip.text = title_text",
        "        strip.location = (0.5, 0.7)",
        "        strip.align_y = 'TOP'",
        "        strip.align_x = 'CENTER'",
        "        strip.font_size = 150",
        "        strip.color = (1.0, 1.0, 1.0)",
        "        strip.frame_final_duration = duration",
        "        ",
        "        current_frame += duration",
        "",
        "",
        "def main():",
        f'    media_dir = r"{media_dir}"',
        f'    output_path = r"{output_blend}"',
    ]

    if template_path:
        script_lines.append(f'    template_path = r"{template_path}"')
    else:
        script_lines.append("    template_path = None")

    if thumbnail_path:
        script_lines.append(f'    thumbnail_path = r"{thumbnail_path}"')
    else:
        script_lines.append("    thumbnail_path = None")

    script_lines.extend([
        f"    changelog_sections = {repr(changelog_sections)}",
        "",
        "    loaded = load_template(template_path)",
        "    if not loaded:",
        "        clear_sequencer()",
        f"    setup_scene_settings({resolution_x}, {resolution_y}, {fps})",
        "",
        "    start_frame = add_thumbnail(thumbnail_path)",
        "",
        "    video_files = [",
    ])

    for video in video_files:
        script_lines.append(f'        r"{video}",')

    script_lines.extend(
        [
            "    ]",
            "",
            "    end_frame = add_video_clips(media_dir, video_files, "
            "start_frame)",
            "    ",
            "    if changelog_sections:",
            "        add_text_overlays(changelog_sections, end_frame + 30)",
            "    ",
            "    bpy.ops.wm.save_as_mainfile(filepath=output_path)",
            '    print(f"Blender project saved to: {output_path}")',
            "",
            "",
            "if __name__ == '__main__':",
            "    main()",
        ]
    )

    return "\n".join(script_lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate Blender setup script for video project."
    )
    parser.add_argument(
        "media_dir",
        help="Directory containing video files",
    )
    parser.add_argument(
        "-o",
        "--output",
        help="Output .blend file path",
        default="draft_edit.blend",
    )
    parser.add_argument(
        "-c",
        "--changelog",
        help="Path to CHANGELOG.md for text overlays",
        default=None,
    )
    parser.add_argument(
        "-r",
        "--resolution",
        help="Resolution as WIDTHxHEIGHT (default: 1920x1080)",
        default="1920x1080",
    )
    parser.add_argument(
        "-f",
        "--fps",
        help="Frames per second (default: 30)",
        type=int,
        default=30,
    )
    parser.add_argument(
        "-s",
        "--script-output",
        help="Output path for generated Blender Python script",
        default="setup_project.py",
    )
    parser.add_argument(
        "-t",
        "--template",
        help="Path to template .blend file",
        default=None,
    )
    parser.add_argument(
        "--thumbnail",
        help="Path to thumbnail image",
        default=None,
    )
    parser.add_argument(
        "--auto-find",
        action="store_true",
        help="Automatically find template and thumbnail from media dir",
    )

    args = parser.parse_args()

    resolution_parts = args.resolution.lower().split("x")
    if len(resolution_parts) != 2:
        print(
            "Error: Resolution must be in WIDTHxHEIGHT format", file=sys.stderr
        )
        sys.exit(1)

    try:
        res_x = int(resolution_parts[0])
        res_y = int(resolution_parts[1])
    except ValueError:
        print("Error: Resolution values must be integers", file=sys.stderr)
        sys.exit(1)

    changelog_path = args.changelog
    if changelog_path is None:
        changelog_path = Path("CHANGELOG.md")
        if not changelog_path.exists():
            changelog_path = None

    template_path = args.template
    thumbnail_path = args.thumbnail

    if args.auto_find:
        media_dir_path = Path(args.media_dir)
        if not template_path:
            template_path = find_previous_blend_file(media_dir_path)
            if template_path:
                print(f"Found template: {template_path}")
        if not thumbnail_path:
            thumbnail_path = find_thumbnail(media_dir_path)
            if thumbnail_path:
                print(f"Found thumbnail: {thumbnail_path}")

    script_content = generate_blender_script(
        media_dir=args.media_dir,
        output_blend=args.output,
        changelog_path=changelog_path,
        resolution_x=res_x,
        resolution_y=res_y,
        fps=args.fps,
        template_path=template_path,
        thumbnail_path=thumbnail_path,
    )

    script_path = Path(args.script_output)
    script_path.write_text(script_content, encoding="utf-8")

    print(f"Generated Blender setup script: {script_path}")
    print(f"Run with: blender --background --python {script_path}")


if __name__ == "__main__":
    main()
